In [9]:
import math
sin=5
math.sin(1), sin

(0.8414709848078965, 5)

In [6]:
sys.stdout

In [5]:
import sys

In [13]:
from math import sin
sin=5
sin(5), sin

TypeError: 'int' object is not callable

In [14]:
# python -m pip install numpy
import numpy as np


In [16]:
np.array([1, 2, 3]), [1, 2, 3]

(array([1, 2, 3]), [1, 2, 3])

In [23]:
np.arange(3, 5.0 ** 2, 1/3)

array([ 3.        ,  3.33333333,  3.66666667,  4.        ,  4.33333333,
        4.66666667,  5.        ,  5.33333333,  5.66666667,  6.        ,
        6.33333333,  6.66666667,  7.        ,  7.33333333,  7.66666667,
        8.        ,  8.33333333,  8.66666667,  9.        ,  9.33333333,
        9.66666667, 10.        , 10.33333333, 10.66666667, 11.        ,
       11.33333333, 11.66666667, 12.        , 12.33333333, 12.66666667,
       13.        , 13.33333333, 13.66666667, 14.        , 14.33333333,
       14.66666667, 15.        , 15.33333333, 15.66666667, 16.        ,
       16.33333333, 16.66666667, 17.        , 17.33333333, 17.66666667,
       18.        , 18.33333333, 18.66666667, 19.        , 19.33333333,
       19.66666667, 20.        , 20.33333333, 20.66666667, 21.        ,
       21.33333333, 21.66666667, 22.        , 22.33333333, 22.66666667,
       23.        , 23.33333333, 23.66666667, 24.        , 24.33333333,
       24.66666667])

In [25]:
np.linspace(2, 5.0001, 7)

array([2.        , 2.50001667, 3.00003333, 3.50005   , 4.00006667,
       4.50008333, 5.0001    ])

In [27]:
np.random.random(5)

array([0.13499634, 0.04081371, 0.87216079, 0.97993127, 0.76943993])

In [34]:
a = np.array([[1, 2.1, 3], [3, 14.433453, 8]])

In [35]:
a.T

array([[ 1.      ,  3.      ],
       [ 2.1     , 14.433453],
       [ 3.      ,  8.      ]])

In [36]:
a.ravel()

array([ 1.      ,  2.1     ,  3.      ,  3.      , 14.433453,  8.      ])

In [37]:
a.reshape([6, 1])

array([[ 1.      ],
       [ 2.1     ],
       [ 3.      ],
       [ 3.      ],
       [14.433453],
       [ 8.      ]])

In [40]:
np.arange(20).reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [44]:
np.zeros([3, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
b = np.arange(24).reshape(3, 2, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [55]:
b[:,1, :3]

array([[ 4,  5,  6],
       [12, 13, 14],
       [20, 21, 22]])

In [57]:
b ** 2

array([[[  0,   1,   4,   9],
        [ 16,  25,  36,  49]],

       [[ 64,  81, 100, 121],
        [144, 169, 196, 225]],

       [[256, 289, 324, 361],
        [400, 441, 484, 529]]], dtype=int32)

In [60]:
np.sin(b)

array([[[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
        [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ]],

       [[ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
        [-0.53657292,  0.42016704,  0.99060736,  0.65028784]],

       [[-0.28790332, -0.96139749, -0.75098725,  0.14987721],
        [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 ]]])

In [69]:
np.arange(6).reshape([2, 3]) + np.arange(3)

array([[0, 2, 4],
       [3, 5, 7]])

In [72]:
m = np.random.random(9).reshape(3, 3)
v = np.array([1, 2, 3])
m, v

(array([[0.76126454, 0.08969586, 0.20611019],
        [0.10364048, 0.10419853, 0.28866078],
        [0.41215059, 0.69334038, 0.73013121]]), array([1, 2, 3]))

In [73]:
m * v

array([[0.76126454, 0.17939173, 0.61833056],
       [0.10364048, 0.20839706, 0.86598233],
       [0.41215059, 1.38668076, 2.19039364]])

In [74]:
m @ v

array([1.55898683, 1.17801987, 3.98922499])

In [78]:
m > 0.5

array([[ True, False, False],
       [False, False, False],
       [False,  True,  True]])

In [89]:
m

array([[0.76126454, 0.08969586, 0.20611019],
       [0.10364048, 0.10419853, 0.28866078],
       [0.41215059, 0.69334038, 0.73013121]])

In [91]:
m[:][2]

array([0.41215059, 0.69334038, 0.73013121])

In [ ]:
mm = [[1, 2, 3]] * 3
mm[:][2]

In [95]:
i = [1, 2]
m[i], m[1], m[2]

(array([[0.10364048, 0.10419853, 0.28866078],
        [0.41215059, 0.69334038, 0.73013121]]),
 array([0.10364048, 0.10419853, 0.28866078]),
 array([0.41215059, 0.69334038, 0.73013121]))

In [108]:
n = np.arange(10) * 10
n[[3, 7, 9]]
n[[True, False, False, *([True] * 7)]]


array([ 0, 30, 40, 50, 60, 70, 80, 90])

In [118]:
m[np.random.random(9).reshape(3, 3) > 0.5]

array([0.76126454, 0.08969586, 0.20611019, 0.10364048, 0.10419853,
       0.41215059, 0.73013121])

In [114]:
m[m < 0.5]

array([0.08969586, 0.20611019, 0.10364048, 0.10419853, 0.28866078,
       0.41215059])

In [124]:
print(*v)

1 2 3


In [126]:
[ x + 1 for x in v ], v

([2, 3, 4], array([1, 2, 3]))

In [135]:
sum([ x ** 3 for x in range(10000000) ])

2499999500000025000000000000

In [154]:
m, np.sum(m, axis=1)

(array([[0.76126454, 0.08969586, 0.20611019],
        [0.10364048, 0.10419853, 0.28866078],
        [0.41215059, 0.69334038, 0.73013121]]),
 array([1.05707059, 0.49649978, 1.83562218]))

In [138]:
np.sum(np.arange(10000000) ** 3.0)

2.499999500000011e+27

In [143]:
# CSV == Comma-Separated Values
import pandas as pd
d = pd.read_csv('Documents/sample.csv')
d

Фамилия  Счастье
0    Иванов      123
1    Петров     8723
2   Сидоров     2308
3  Васильев     1023

In [148]:
nd = np.array(d['Фамилия'])
nd[nd > 'П']

array(['Петров', 'Сидоров'], dtype=object)

In [159]:
np.append(a, [99, 98]), a

(array([ 1.      ,  2.1     ,  3.      ,  3.      , 14.433453,  8.      ,
        99.      , 98.      ]), array([[ 1.      ,  2.1     ,  3.      ],
        [ 3.      , 14.433453,  8.      ]]))